var ScoreModule = {
      render() {
        if (window.RevenueScoreCenter) return RevenueScoreCenter.render();
        return this.legacyRender();
      },
      legacyRender() {
        const selected = ScoreEngine.getById(App.state.selectedScoreId) || App.state.scores[0];
        return `<div class="grid lg:grid-cols-3 gap-4"><div class="lg:col-span-1 bg-white rounded-3xl p-5 shadow-sm border border-slate-100"><h2 class="text-xl font-black mb-1">Criar Score</h2><p class="text-sm text-slate-500 mb-5">Crie presets de score para plugar nas ações.</p>${this.createForm()}</div><div class="lg:col-span-2 bg-white rounded-3xl p-5 shadow-sm border border-slate-100"><div class="flex items-start justify-between gap-3 mb-5"><div><h2 class="text-xl font-black mb-1">Scores criados</h2><p class="text-sm text-slate-500">Editar um score afeta ações que usam este preset.</p></div><div class="text-3xl font-black">${App.state.scores.length}</div></div><div class="space-y-3 mb-5">${App.state.scores.map(score => this.card(score)).join('')}</div>${selected ? this.editor(selected) : ''}</div></div>`;
      },
      createForm() { return `<div class="space-y-3"><div><label class="text-xs font-black text-slate-500">Nome do score</label><input value="${Utils.escape(App.state.scoreDraft.name)}" oninput="App.state.scoreDraft.name=this.value; App.save();" placeholder="Ex: Score Webinar" class="w-full px-4 py-3 rounded-2xl bg-slate-100 font-semibold" /></div><div><label class="text-xs font-black text-slate-500">Descrição</label><textarea oninput="App.state.scoreDraft.description=this.value; App.save();" placeholder="Quando este score deve ser usado?" class="w-full px-4 py-3 rounded-2xl bg-slate-100 font-semibold min-h-[90px]">${Utils.escape(App.state.scoreDraft.description)}</textarea></div><div class="rounded-3xl bg-slate-50 border border-slate-100 p-4"><div class="flex items-center justify-between gap-3 mb-3"><h3 class="font-black">Tags do score</h3><span class="text-xs font-black text-slate-400">tag / pontos</span></div><div class="space-y-2">${App.state.scoreDraft.tagRules.map((rule, index) => this.draftTagRow(rule, index)).join('')}</div><button onclick="Actions.addScoreDraftTag()" class="mt-3 px-4 py-2 rounded-xl bg-slate-900 text-white font-bold">+ Nova tag</button></div><button onclick="Actions.createScorePreset()" class="w-full px-5 py-3 rounded-2xl bg-slate-900 text-white font-black">Criar score</button></div>`; },
      draftTagRow(rule, index) { return `<div class="grid grid-cols-[minmax(0,1fr)_72px_40px] gap-2 items-center"><input value="${Utils.escape(rule.tag)}" oninput="App.state.scoreDraft.tagRules[${index}].tag=this.value; App.save();" placeholder="#tag" class="min-w-0 px-3 py-2 rounded-xl bg-white border border-slate-200 font-bold" /><input type="number" value="${Number(rule.score || 0)}" onfocus="if(this.value==='0') this.value=''" onblur="if(this.value==='') this.value='0'" oninput="App.state.scoreDraft.tagRules[${index}].score=Number(this.value || 0); App.save();" class="min-w-0 px-2 py-2 rounded-xl bg-white border border-slate-200 font-black" /><button onclick="Actions.removeScoreDraftTag(${index})" title="Excluir tag" class="w-10 h-10 bg-red-100 rounded-xl font-black flex items-center justify-center">×</button></div>`; },
      card(score) { const actionCount = App.state.actions.filter(action => action.scoreId === score.id).length; return `<div onclick="Actions.selectScore(${score.id})" class="cursor-pointer p-4 rounded-3xl border ${App.state.selectedScoreId === score.id ? 'border-slate-900 bg-slate-50' : 'border-slate-100 bg-slate-50'} hover:bg-slate-100"><div class="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h3 class="font-black text-lg">${Utils.escape(score.name)}</h3><p class="text-sm text-slate-500">${Utils.escape(score.description || 'Sem descrição')}</p><p class="text-xs text-slate-400 mt-1">${score.tagRules.length} tag(s) • ${actionCount} ação(ões) usando</p></div><span class="px-3 py-1 rounded-full bg-white border border-slate-200 text-xs font-black">Score</span></div></div>`; },
      editor(score) { return `<div class="rounded-3xl bg-slate-50 border border-slate-100 p-5"><h3 class="text-lg font-black mb-3">Editar score selecionado</h3><div class="grid md:grid-cols-1 gap-3 mb-3"><div><label class="text-xs font-black text-slate-500">Nome</label><input value="${Utils.escape(score.name)}" oninput="Actions.updateScoreField(${score.id}, 'name', this.value, false)" class="w-full px-4 py-3 rounded-2xl bg-white border border-slate-200 font-semibold" /></div><div><label class="text-xs font-black text-slate-500">Descrição</label><textarea oninput="Actions.updateScoreField(${score.id}, 'description', this.value, false)" class="w-full px-4 py-3 rounded-2xl bg-white border border-slate-200 font-semibold min-h-[80px]">${Utils.escape(score.description)}</textarea></div></div><div class="space-y-2">${score.tagRules.map((rule, index) => `<div class="grid grid-cols-[minmax(0,1fr)_72px_40px] gap-2 items-center"><input value="${Utils.escape(rule.tag)}" oninput="Actions.updateScoreTag(${score.id}, ${index}, 'tag', this.value, false)" class="min-w-0 px-3 py-2 rounded-xl bg-white border border-slate-200 font-bold" /><input type="number" value="${Number(rule.score || 0)}" onfocus="if(this.value==='0') this.value=''" onblur="if(this.value==='') this.value='0'" oninput="Actions.updateScoreTag(${score.id}, ${index}, 'score', Number(this.value || 0), false)" class="min-w-0 px-2 py-2 rounded-xl bg-white border border-slate-200 font-black" /><button onclick="Actions.removeScoreTag(${score.id}, ${index})" title="Excluir tag" class="w-10 h-10 bg-red-100 rounded-xl font-black flex items-center justify-center">×</button></div>`).join('')}</div><button onclick="Actions.addScoreTag(${score.id})" class="mt-3 px-4 py-2 rounded-xl bg-slate-900 text-white font-bold">+ Nova tag neste score</button></div>`; }
    };
window.ScoreModule = ScoreModule;
